config/routes.rb
Rails.application.routes.draw do
 

  get 'categories/about',to:'categories#about'
resources  :categories do
	resources :workout_categories do
		resources :exercises do
			put 'Upvote' => 'exercises#up'
			put 'Downvote' => 'exercises#down'
			post 'favorite'=>'favorites#create'
			delete 'favorite'=>'favorites#destroy'
		end
	end
end
get '/map', to: 'map#index'
get '/exercises/new', to: 'exercises#new'
get '/signup', to:'users#new'
post '/users',to:'users#create'
get '/login',to:"sessions_controller#new"
post '/login',to:"sessions_controller#create"
delete '/logout',to:"sessions_controller#destroy"
post '/categories', to: "categories#create"
resources :users   

  root 'categories#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :workout_categories
end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
	belongs_to :workout_category
	has_many :favorites
	has_many :users,through: :favorites

	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
	belongs_to :user
	belongs_to :exercise
end

app/models/map.rb
class Map < ActiveRecord::Base
def index
end
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :favorites
	has_many :exercises, through: :favorites
	validates :user_name, presence: true, length:{minimum:5}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX  }
	has_secure_password
	end

app/models/workout_category.rb
class WorkoutCategory < ActiveRecord::Base
	has_many :exercises
	belongs_to :category
		
	validates :name,presence: true, length:{minimum:4}
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :authorize
	def index


		@categories = Category.all
	end
	def about
	end
	def show
		@workout = Category.find(params[:id])
		@workout_categories = @workout.workout_categories
	end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
	before_filter :authorize
	def new
		@exercise=Exercise.new
		@workout_category=WorkoutCategory.find(params[:workout_category_id])
	end
	def show
		@exercise = Exercise.find(params[:id])
	end

	def down
		@exercise = Exercise.find(params[:exercise_id])
		@exercise.votes = @exercise.votes - 1
		@exercise.save
		redirect_to category_workout_category_exercise_path(:category_id,:workout_category_id,@exercise) 
	end
	def up
		@exercise = Exercise.find(params[:exercise_id])
		@exercise.votes = @exercise.votes + 1
		@exercise.save
		redirect_to category_workout_category_exercise_path(:category_id,:workout_category_id,@exercise) 
	end
	def create
		@category=Category.find(params[:category_id])
		@exercise=WorkoutCategory.find(params[:workout_category_id]).exercises.build(exercise_params)
		if @exercise.save
			redirect_to category_path(@category)
		else
			redirect_to new_category_workout_category_exercise_path(@category,@workout_category)
		end
	end
	private
	def exercise_params
		params.require(:exercise).permit(:name,:image,:difficulty,:equipment,:category_id,:workout_category_id)
	end
		

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	before_filter :authorize
	def create
		@favorite=Favorite.new(favorite_params)
		@exercise = Exercise.find(params[:exercise_id])
		@favorite.user_id=@current_user.id
		if @favorite.save
			redirect_to category_workout_category_exercise_path(:category_id,:workout_category_id,@exercise)

		else
			redirect_to root_path
		end
	end
	def favorite_params
		params.permit(:user_id,:exercise_id)
	end
end

app/controllers/map_controller.rb
class MapController < ApplicationController

def index
@tweets = $twitter.search("#ampufit -rt", :geocode => ["38.89","-77.03","10km"], :include_entities => false).take(50)
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_filter :authorize,except:[:new,:create]
	def new
	end
	def create 
		user=User.new(user_params)
		if user.save
			session[:user_id]=user.id
			redirect_to '/'
		else
			redirect_to '/signup'
		end

	end
	def show
		@user = User.find(params[:id])
		@favorites = @user.favorites.all
	end
	helper_method :current_user
	private 
	def user_params
	    params.require(:user).permit(:user_name, :email, :password,:password_confirmation) 
    end
end

app/controllers/workouts_controller.rb
class WorkoutsController < ApplicationController
	before_filter :authorize
	def new
		@workout=Workout.new
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/map_helper.rb
module MapHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/workouts_helper.rb
module WorkoutsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmpUFit</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href='https://fonts.googleapis.com/css?family=Noto+Sans:400,700' rel='stylesheet' type='text/css'>
  <%= csrf_meta_tags %>
</head>
<body>
<header id="scrollable">
  <div class="row">
    <div class="col-md-1" id="tit_bar">
      <h4>AmpUFit</h4>
    </div>
	<% if !current_user%>
		<div class="col-md-6" id="sign_in_header">
				<%=form_tag '/login' do%>

					Email: <%=text_field_tag :email%>
					Password: <%=password_field_tag :password%>
					<%=submit_tag "Submit"%>
					<%= hidden_field_tag 'authenticity_token', form_authenticity_token %>
				<%end%>
		</div>
		<div class="col-md-2" id="sign_up_header">
	         		<p class="header_login">New user? <%= link_to "Sign up now!", signup_path %></p>
	
	 	</div>
	<%else%>
		<div class="col-md-4">
			<p><%=@current_user.email unless @current_user==nil%></p>
		</div>
		<div class="col-md-4">
			<%=button_to "Logout",logout_path,method: :delete,html:{class:"btn btn-sm"}%>
		</div>
	<%end%>
    <div class="col-md-3">
	<div class="dropdown">
		<button class="btn btn-default  dropdown-toggle" type="button" data-toggle="dropdown"><span class="glyphicon glyphicon-align-center" aria-hidden="true"></span></button>
		<ul class="dropdown-menu">
			<li><%=link_to "About",categories_about_path%></li>
			<li><%=link_to "Home",root_path%></li>
			<%if @current_user!=nil%>
				<li><%=link_to "My Account",user_path(@current_user.id) %></li>
			<%end%>
			<li><%=link_to "Sign up",signup_path%></li>
			<li><%=link_to "Map",map_path%></li>
		</ul>
		</div>

    </div>
  </div>
</header>
 <div class="row">
        <div class="jumbotron">
          <h1 class="headline"><%=link_to"#{image_tag"LogoAUFwb",id:"logo"}".html_safe,root_path%></h1>
		  <h3 class="headline">Amp up your fitness!</h3>
        </div>
	  </div>


<div id="main-container" class="container">
               <%= yield %>
      </div>
    </div>

</body>
</html>